[package]
name = "secret-value"
version = "0.1.0"
authors = ["Kitsu <mail@kitsu.me>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"], optional = true }

[dev-dependencies]
serde_test = "1.0.57"
