name: CI

on:
  - push

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry2-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Cache cargo target dir
      uses: actions/cache@v1.1.2
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Check format
      run: cargo fmt -- --check

    - name: Lint
      run: 
        - cargo clippy -- -D warnings
        - cargo clippy --all-features -- -D warnings

    - name: Build
      run:
        - cargo build
        - cargo build --all-features

    - name: Test
      run: 
        - cargo test
        - cargo test --all-features
